[package]
name = "zkhack-lisbon"
version = "0.1.0"
edition = "2021"

[dependencies]
miden_vm = { version = "0.5.0", package = "miden-vm", features = ["concurrent"]}
miden-stdlib = "0.4.0"
twenty-first = "0.19.1"
